networks:
  comfycowboy_default:
    external: false

services:
  mariadb:
    profiles: [desktop]
  rabbitmq:
    profiles: [desktop]
  clipCowboy_bot:
    profiles: [desktop]

  pipeline:
    build:
      context: .
      args:
        REQUIREMENTS: requirements.sparky.txt
    environment:
      - DATABASE_HOST=192.168.1.114
      - RABBITMQ_HOST=192.168.1.114
      - ANALYZE_WORKERS=5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:
